### ISSUE TITLE
Conditional comments are not parsed between doctype and html...

### ISSUE THREAD

**Issue by josejuanmontiel** [thymeleaf/thymeleaf-extras-conditionalcomments#3]
Hi,

i'm trying generating something like this... with no luck...

``` html
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="no-js ie ie6 lt-ie10 lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie ie7 lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie ie8 lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9 ]>    <html class="no-js ie ie9 lt-ie10"> <![endif]-->
<!--[if IE 10]>    <html class="no-js ie ie10"><![endif]-->
<!--[if (gt IE 10)|!(IE)]><!--> <html class="no-js"> <!--<![endif]-->
<head>
```

It's my problem...? or maybe not implemented because it is outside <html> tag.

I'm using 2.0.16 thymeleaf with 2.0.0 version of extras-conditionalcomments.

Thanks in advance.

**Comment by josejuanmontiel** [comment]
If i put in simple template... works, but if i put this in a layout, don't work. keep searching.

**Comment by josejuanmontiel** [comment]
maybe the problem its mine... i put conditionals in layout and not in the template... my mistake.

Sorry.

**Comment by ultraq** [comment]
If by 'layout' you mean the layout dialect, then it might be a problem with that and you can raise an issue on that project's GitHub.  I'd ask you to check that the conditional comments appear in the resulting HTML first.  If they do, then there might be something going on between the interaction of both of those dialects.

Anyway, looking at the conditional comment you're trying to make (after I edited your comment so that the code showed - GitHub removes code otherwise), that last line looks redundant and can probably be changed to just:

``` html
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="no-js ie ie6 lt-ie10 lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie ie7 lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie ie8 lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9 ]>    <html class="no-js ie ie9 lt-ie10"> <![endif]-->
<!--[if IE 10]>    <html class="no-js ie ie10"><![endif]-->
<html class="no-js">
<head>
```
